version: '3.4'

services:

  bol-validator-1:
    image: bol-validator-1
    environment:
      ASPNETCORE_ENVIRONMENT : Development
    build:
      context: .
      dockerfile: Bol.Api/Dockerfile
    volumes:
      - ../validators/validator-1.json:/app/wallet.json
    ports:
      - "11333:21333"
    networks:
        - bol-network

  bol-validator-2:
    image: bol-validator-2
    environment:
      ASPNETCORE_ENVIRONMENT : Development
    build:
      context: .
      dockerfile: Bol.Api/Dockerfile
    volumes:
      - ../validators/validator-2.json:/app/wallet.json
    ports:
      - "12333:21333"   
    networks:
        - bol-network

  bol-validator-3:
    image: bol-validator-3
    environment:
      ASPNETCORE_ENVIRONMENT : Development
    build:
      context: .
      dockerfile: Bol.Api/Dockerfile
    volumes:
      - ../validators/validator-3.json:/app/wallet.json
    ports:
      - "13333:21333"
    networks:
        - bol-network

  bol-validator-4:
    image: bol-validator-4
    environment:
      ASPNETCORE_ENVIRONMENT : Development
    build:
      context: .
      dockerfile: Bol.Api/Dockerfile
    volumes:
      - ../validators/validator-4.json:/app/wallet.json
    ports:
      - "14333:21333"     
    networks:
        - bol-network

  api-node:
    image: api-node
    environment:
      ASPNETCORE_ENVIRONMENT : Development
    build:
      context: .
      dockerfile: Bol.Api/Dockerfile
    ports:
      - "5000:8080"
      - "21332:21332"
    networks:
        - bol-network
                
networks:
  bol-network: