version: '3.4'

services:

  bol-validator-1:
    image: bol-validator-1
    environment:
      ASPNETCORE_ENVIRONMENT : Development
    build:
      context: .
      dockerfile: Bol.Api/Validator.Dockerfile
      args:
        validator_wallet : validator-1.json
    ports:
      - "11333:10333"
    networks:
        - bol-network

  bol-validator-2:
    image: bol-validator-2
    environment:
      ASPNETCORE_ENVIRONMENT : Development
    build:
      context: .
      dockerfile: Bol.Api/Validator.Dockerfile
      args:
        validator_wallet : validator-2.json    
    ports:
      - "12333:10333"   
    networks:
        - bol-network

  bol-validator-3:
    image: bol-validator-3
    environment:
      ASPNETCORE_ENVIRONMENT : Development
    build:
      context: .
      dockerfile: Bol.Api/Validator.Dockerfile
      args:
        validator_wallet : validator-3.json      
    ports:
      - "13333:10333"
    networks:
        - bol-network

  bol-validator-4:
    image: bol-validator-4
    environment:
      ASPNETCORE_ENVIRONMENT : Development
    build:
      context: .
      dockerfile: Bol.Api/Validator.Dockerfile
      args:
        validator_wallet : validator-4.json
    ports:
      - "14333:10333"     
    networks:
        - bol-network

  api-node:
    image: api-node
    environment:
      ASPNETCORE_ENVIRONMENT : Development
    build:
      context: .
      dockerfile: Bol.Api/Dockerfile
    ports:
      - "8000:80"
      - "10332:10332"
    networks:
        - bol-network
                
networks:
  bol-network: