version: '3.4'

services:

  # node1:
    # image: bol-node1
    # environment:
      # ASPNETCORE_ENVIRONMENT : Development
    # build:
      # context: .
      # dockerfile: Bol.Api/Validator.Dockerfile
      # args:
        # validator_wallet : val1.json
    # extra_hosts:
      # - "node1:host.docker.internal"      
    # ports:
      # - "11456:11456"
      # - "5000:5000"
    # networks:
        # - bol-network

  node2:
    image: bol-node2
    environment:
      ASPNETCORE_ENVIRONMENT : Development
    build:
      context: .
      dockerfile: Bol.Api/Validator.Dockerfile
      args:
        validator_wallet : val2.json
    extra_hosts:
      - "node1:${MACHINE_IP}"        
    ports:
      - "11457:11456"   
    networks:
        - bol-network

  node3:
    image: bol-node3
    environment:
      ASPNETCORE_ENVIRONMENT : Development
    build:
      context: .
      dockerfile: Bol.Api/Validator.Dockerfile
      args:
        validator_wallet : val3.json
    extra_hosts:
      - "node1:${MACHINE_IP}"           
    ports:
      - "11458:11456"
    networks:
        - bol-network

  node4:
    image: bol-node4
    environment:
      ASPNETCORE_ENVIRONMENT : Development
    build:
      context: .
      dockerfile: Bol.Api/Validator.Dockerfile
      args:
        validator_wallet : val4.json
    extra_hosts:
      - "node1:${MACHINE_IP}"      
    ports:
      - "11459:11456"     
    networks:
        - bol-network

  api-node:
    image: api-node
    environment:
      ASPNETCORE_ENVIRONMENT : Development
    build:
      context: .
      dockerfile: Bol.Api/Dockerfile
    extra_hosts:
      - "node1:${MACHINE_IP}"    
    ports:
      - "5000:80"
    networks:
        - bol-network
                
networks:
  bol-network: