version: '3.4'

services:

  # bol-validator-1:
    # image: bol-validator-1
    # environment:
      # ASPNETCORE_ENVIRONMENT : Development
    # build:
      # context: .
      # dockerfile: Bol.Api/Validator.Dockerfile
      # args:
        # validator_wallet : validator-1.json
    # extra_hosts:
      # - "bol-validator-1:host.docker.internal"      
    # ports:
      # - "11456:11456"
      # - "5000:5000"
    # networks:
        # - bol-network

  bol-validator-2:
    image: bol-validator-2
    environment:
      ASPNETCORE_ENVIRONMENT : Development
    build:
      context: .
      dockerfile: Bol.Api/Validator.Dockerfile
      args:
        validator_wallet : validator-2.json
    extra_hosts:
      - "bol-validator-1:${MACHINE_IP}"        
    ports:
      - "11457:11456"   
    networks:
        - bol-network

  bol-validator-3:
    image: bol-validator-3
    environment:
      ASPNETCORE_ENVIRONMENT : Development
    build:
      context: .
      dockerfile: Bol.Api/Validator.Dockerfile
      args:
        validator_wallet : validator-3.json
    extra_hosts:
      - "bol-validator-1:${MACHINE_IP}"           
    ports:
      - "11458:11456"
    networks:
        - bol-network

  bol-validator-4:
    image: bol-validator-4
    environment:
      ASPNETCORE_ENVIRONMENT : Development
    build:
      context: .
      dockerfile: Bol.Api/Validator.Dockerfile
      args:
        validator_wallet : validator-4.json
    extra_hosts:
      - "bol-validator-1:${MACHINE_IP}"      
    ports:
      - "11459:11456"     
    networks:
        - bol-network

  api-node:
    image: api-node
    environment:
      ASPNETCORE_ENVIRONMENT : Development
    build:
      context: .
      dockerfile: Bol.Api/Dockerfile
    extra_hosts:
      - "bol-validator-1:${MACHINE_IP}"    
    ports:
      - "5000:80"
    networks:
        - bol-network
                
networks:
  bol-network: