apiVersion: v1
kind: ConfigMap
metadata:
  name: tcp-services
  namespace: nginx
data:
  21604: "bol-demo/bol-validator-1:21333"
  21614: "bol-demo/bol-validator-2:21333"
  21624: "bol-demo/bol-validator-3:21333"
  21634: "bol-demo/bol-validator-4:21333"
  21644: "bol-demo/bol-validator-5:21333"
  21654: "bol-demo/bol-validator-6:21333"
  21664: "bol-demo/bol-validator-7:21333"
  21674: "bol-demo/bol-validator-8:21333"
  21684: "bol-demo/bol-validator-9:21333"
  21694: "bol-demo/bol-validator-10:21333"